### ISSUE TITLE
RPC ERROR

### ISSUE THREAD

**Issue by WaReZoR-UA** [BixBite-project/bixbite#2]
![image](https://user-images.githubusercontent.com/38248645/40851857-40b9b0de-65d1-11e8-8959-5c2562e1fb8a.png)
![image](https://user-images.githubusercontent.com/38248645/40851915-6c40645a-65d1-11e8-9848-a54617de3b94.png)

doesn't see quantity of coins in the block

**Comment by BixBite-project** [comment]
Pool errors do not related to daemon workability. anyway, after mainnet starts, everyone must use latest pre-compiled package

**Comment by WaReZoR-UA** [comment]
and I did as you wrote
